config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root      'static_pages#home'
  get       '/help',        to: 'static_pages#help'
  get       '/contact',     to: 'static_pages#contact'
  get       '/signup',      to: 'users#new'
  get       '/login',       to: 'sessions#new'
  post      '/login',       to: 'sessions#create'
  delete    '/logout',      to: 'sessions#destroy'
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
    belongs_to :user
    has_secure_password
end

app/models/group.rb
class Group < ApplicationRecord
    has_one(:users)
end

app/models/user.rb
class User < ApplicationRecord

    attr_accessor :remember_token

    before_save { self.email = email.downcase }
    VALID_NUMBER_REGEX = /\A[0-9]*\z/
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates(:name, presence: true, length: {maximum: 50})
    validates(:email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false})
    validates(:id_number, presence: true, length: {is: 16}, uniqueness: true)
    validates(:password, presence: true, length: {minimum: 6}, allow_nil: true)

    has_secure_password

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in user
            params[:session][:remember_me] == '1' ? remember(user) : forget(user)
            redirect_back_or user
        else
            flash.now[:danger] = 'Invalid email/password combination'
            render 'new'
        end
    end

    def destroy
        log_out if logged_in?
        redirect_to root_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:edit, :update]
    before_action :correct_user, only: [:edit, :udpate]

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            flash[:success] = "Welcome to the sample app!"
            redirect_to @user
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            flash[:success] = "Profile updated"
            redirect_to @user
        else
            render 'edit'
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :id_number, :password, :password_confirmation)
    end
    
    # Confirms a logged-in user
    def logged_in_user
        unless logged_in?
            store_location
            flash[:danger] = "Please log in."
            redirect_to login_url
        end
    end

    # Confirms the correct user
    def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end

    #Remembers a user in a persistent session
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    # Returns true if the given user is the current user
    def current_user?(user)
        user == current_user
    end

    # Returns the current logged-in user (if any)
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    # Return true if the user is logged in, false otherwise
    def logged_in?
        !current_user.nil?
    end

    # Forgets a persistent session
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    # Logs out the current user
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    # Redirects to stored location (or to the default)
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end

    # Stores the URL trying to be accessed
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

    #Return the Gravatar for the given user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The Legalito App
        by Legalito
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", '#' %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <%= link_to "legalito_app", root_path, id: "logo" %>
                <nav>
                    <ul class="nav navbar-nav navbar-right">
                        <li><%= link_to "Home", root_path %></li>
                        <% if logged_in? %>
                            <li><%= link_to "Users", '#' %></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Account<b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><%= link_to "Profile", current_user %></li>
                                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                                    <li class="divider"></li>
                                    <li>
                                        <%= link_to "Log out", logout_path, method: "delete" %>
                                    </li>
                                </ul>
                            </li>
                        <% else %>
                            <li><%= link_to "Log in", login_path %></li>
                        <% end %>
                    </ul>
                </nav>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
          <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
          </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title>Legalito | <%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>

        <%= render 'layouts/shim' %>

    </head>

    <body>
        <%= render 'layouts/header' %>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <% flash.each do |message_type, message| %>
                        <div class="alert alert-<%= message_type %>"><%= message %></div>
                    <% end %>

                    <%= yield %>
                    <%= render 'layouts/footer' %>
                    <%= debug(params) if Rails.env.development? %>

                </div>
                <div class="col-md-1"></div>
            </div>
        </div>

    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Legalito team about potential partnership at partner@legalito.com
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "help") %>
<h1>Help</h1>
<p>
    Get help on rails at
    <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to the Legalito</h1>

    <h2>
        This is the home page for the Legalito application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :id_number %>
            <%= f.text_field :id_number, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>

        <div class="gravatar_edit">
            <%= gravatar_for @user %>
            <a href="http://gravatar.com/emails" target="_blank">change</a>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :id_number %>
            <%= f.text_field :id_number, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>